## Public Service (LoadBalancer)
## - Creates an external IP for the Deployment
## - Costs: charged while active; consider using port-forward during development
apiVersion: v1
kind: Service
metadata:
  name: mnist-inference-svc
spec:
  type: LoadBalancer
  selector:
    app: mnist-inference
  ports:
    - port: 80
      targetPort: 8080
